name: mymemberlink
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  email_otp: ^3.0.2
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  image: ^4.3.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.2.0
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/team.png
      - assets/images/camera.png
      - assets/bg/mainscreenbg.png
      - assets/bg/memberlink.png
      - assets/bg/cart.png
      - assets/bg/bulletinappbar.png
      - assets/bg/productappbar.png
      - assets/images/na.png
      - assets/gif/dribbble-success-2.gif
      - assets/gif/trash-bin.gif
      - assets/gif/pencil.gif
      - assets/animations/
